import {isWorkday,coverageForDay,isUnavailable,holidayType} from './utils.js';
export function evaluateDay(day,state){const issues=[]; if(!isWorkday(day,state))return {issues}; const cov=coverageForDay(day,state); const sched=state.schedule[day]||{morning:[],evening:[]}; const type=holidayType(day,state); if(type==='global_closed'){if((sched.morning||[]).length||(sched.evening||[]).length)issues.push({date:day,message:'Día de cierre global: no debería haber turnos asignados'}); return {issues};}
 const effM=(sched.morning||[]).filter(id=>!unav(id,day,state)); const effE=(sched.evening||[]).filter(id=>!unav(id,day,state));
 if(effM.length<cov.morning)issues.push({date:day,message:`Mañana sin cobertura: ${effM.length}/${cov.morning}`}); if(effE.length<cov.evening)issues.push({date:day,message:`Tarde sin cobertura: ${effE.length}/${cov.evening}`});
 const both=effM.filter(id=>effE.includes(id)); if(both.length)issues.push({date:day,message:`Asignado en ambos turnos: ${both.map(id=>name(id,state)).join(', ')}`});
 const seniorE=effE.filter(id=>role(id,state)==='senior').length; const standardE=effE.filter(id=>role(id,state)!=='senior').length;
 if(cov.evening===2 && effE.length>0 && (seniorE!==1 || standardE!==1))issues.push({date:day,message:'El turno de tarde debe tener 1 senior + 1 estándar'});
 [...(sched.morning||[]),...(sched.evening||[])].forEach(id=>{if(unav(id,day,state))issues.push({date:day,message:`${name(id,state)} está de vacaciones y asignado`})}); return {issues};}
export function evaluateMonth(y,m,state){let issues=[];for(let d=new Date(y,m,1);d.getMonth()===m;d.setDate(d.getDate()+1))issues=issues.concat(evaluateDay(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,state).issues);return {issues}}
function role(id,state){return state.users.find(u=>u.id===id)?.role||'standard'}function name(id,state){return state.users.find(u=>u.id===id)?.name||id}function unav(id,day,state){const u=state.users.find(x=>x.id===id);return u?isUnavailable(u,day):false}
